FROM node:current-alpine

WORKDIR /app

COPY package.json /app/package.json

COPY package-lock.json /app/package-lock.json

COPY tsconfig.json /app/tsconfig.json

RUN npm install

COPY . /app

RUN npm run build

COPY .next /app/.next

EXPOSE 3000

CMD ["npm", "run", "dev"]