export const CURRENT_SERVER = 'CURRENT_SERVER';

export const DELETE_SERVER = 'DELETE_SERVER';

export const ADD_SERVER = 'ADD_SERVER';

export const POPULATE_LIST = 'POPULATE_LIST';

export const CLEAN_METRICS = 'CLEAN_METRICS';

export const UPDATE_METRICS = 'UPDATE_METRICS';

export const CHANGE_METRIC = 'CHANGE_METRIC';

export const NEW_DATE_SELECTED = 'NEW_DATE_SELECTED';

export const DATE_UNSELECTED = 'DATE_UNSELECTED';

export const UPDATE_INTERVAL = 'UPDATE_INTERVAL';

export const TOGGLE_INTERVAL = 'TOGGLE_INTERVAL';

export const NEW_METRIC_SELECTED = 'NEW_METRIC_SELECTED';

export const METRIC_UNSELECTED = 'METRIC_UNSELECTED';

export const UPDATE_SELECTED_METRIC = 'UPDATE_SELECTED_METRIC';

export const UPDATE_USERNAME = 'UPDATE_USERNAME';
